# Generated by Django 3.2.5 on 2021-07-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_customuser_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='company',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='report',
            name='insert_time',
            field=models.DateTimeField(verbose_name='日付'),
        ),
    ]
