# Generated by Django 3.2.5 on 2021-07-15 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20210715_1451'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nippo',
            new_name='Report',
        ),
    ]
