# Generated by Django 3.2.5 on 2021-07-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20210716_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='公開設定'),
        ),
    ]
