# Generated by Django 3.2.5 on 2021-07-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_alter_report_insert_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='insert_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='日付'),
        ),
    ]
